### ISSUE TITLE
ThingSpeak Frontend Integration

### ISSUE THREAD

**Issue by unignoramus11** [avi1o1/GoldAid#2]
Complete the ThingSpeak integration in the frontend.
Vitals and alerts are to be grabbed from two different ThingSpeak channels, each field in a channel representing a separate BSD (two for current implementation).

Vitals format:
`<bsd_id>-<wsd_id>:<temp>,<spo2>,<hr>,<lat>,<lon>;<wsd_id>:...;`

Alerts format (only those WSDs' IDs are filled which have declared an alert status):
`bsd_id-wsd_id;...wsd_id;`

**Comment by VA24d** [comment]
Hello
